In [3]:
#for 1D arrays we can pass either a single value (4) or a tuple ((4,)), same result
a= np.zeros(4)
a= np.zeros((4,))

In [4]:
def function(a):
    print(f"a={a}, a.shape={a.shape}, a.dtype={a.dtype}")

In [7]:
#np.zeros(n): vector of n elements initialised to 0 (float)
a= np.zeros(4)
function(a)
a= np.zeros((4,))
function(a)

a=[0. 0. 0. 0.], a.shape=(4,), a.dtype=float64
a=[0. 0. 0. 0.], a.shape=(4,), a.dtype=float64


In [20]:
#np.arange(n): vector of n elements from 0 to n-1
a=np.arange(10)
function(a)
a=np.arange(10.)
function(a)

a=[0 1 2 3 4 5 6 7 8 9], a.shape=(10,), a.dtype=int32
a=[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], a.shape=(10,), a.dtype=float64


In [22]:
#np.random.rand(n): array of n random numbers between 0 and 1
a=np.random.rand(5)
function(a)
a=np.random.random_sample(5)
function(a)

a=[0.98645905 0.18017651 0.8207218  0.4584531  0.84976883], a.shape=(5,), a.dtype=float64
a=[0.25129083 0.40405429 0.74670112 0.65333184 0.42613079], a.shape=(5,), a.dtype=float64


In [23]:
#all elements in np array are of same datatype:
a=np.array([1,2,3,4]); function(a);
a=np.array([1.,2,3,4]); function(a);

a=[1 2 3 4], a.shape=(4,), a.dtype=int32
a=[1. 2. 3. 4.], a.shape=(4,), a.dtype=float64


In [34]:
#indexing 
a=np.arange(10)
print(f"a[2]={a[2]}, a[2].shape={a[2].shape}")
b=np.array([np.arange(5),2*np.arange(5),3*np.arange(5)])
print(f"b[2]={b[2]}, b[2].shape={b[2].shape}")

a[2]=2, a[2].shape=()
b[2]=[ 0  3  6  9 12], b[2].shape=(5,)


In [35]:
#negative indexes count from end
print(f"a={a}, a[-1]={a[-1]}")

a=[0 1 2 3 4 5 6 7 8 9], a[-1]=9


In [36]:
#try catch block
try:
    c=a[10]
except Exception as e:
    print(f"Error Message: {e}")

Error Message: index 10 is out of bounds for axis 0 with size 10


In [50]:
#slicing [start:stop:step]
x=np.arange(10)
print(f"x[3:7:1]={x[3:7:1]}")
print(f"x[3:9:2]={x[3:9:2]}")
print(f"x[-9:-3:1]={x[-9:-3:1]}")
print(f"x[::2]={x[::2]}")
print(f"x[:3]={x[:3]}")

x[3:7:1]=[3 4 5 6]
x[3:9:2]=[3 5 7]
x[-9:-3:1]=[1 2 3 4 5 6]
x[::2]=[0 2 4 6 8]
x[:3]=[0 1 2]


In [51]:
#np operations: 
a=np.arange(4)
print(f"sum={np.sum(a)}, average={np.mean(a)}, square={a**2}")

sum=6, average=1.5, square=[0 1 4 9]


In [55]:
np.random.seed(1)
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
x=0
for i in range(1000000):
    x+=a[i]*b[i]
toc=time.time()
print(f"∑(a[i]*b[i]) ={x:.2f}, time={1000*(toc-tic):.2f}ms")

tic=time.time()
y=np.dot(a,b)
toc=time.time()
print(f"np.dot(a, b) ={y:.2f}, time={1000*(toc-tic):.2f}ms")

∑(a[i]*b[i]) =249825.02, time=392.62ms
np.dot(a, b) =249825.02, time=1.99ms


In [56]:
del(a)
del(b)

In [57]:
#Matrix
arr= np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [74]:
#Matrix indexing
a= np.arange(6).reshape(3,2)
print(f"a={a}\n")
print(f"a[2]={a[2]}")
print(f"a[2,0]={a[2,0]}")

a=[[0 1]
 [2 3]
 [4 5]]

a[2]=[4 5]
a[2,0]=4


In [75]:
#slicing
a=np.arange(20).reshape(2,10)
print(a,"\n")
print(a[:,3:8:2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

[[ 3  5  7]
 [13 15 17]]
